name: CI

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        id: release-please
        uses: googleapis/release-please-action@v4
        with:
          release-type: node

    outputs:
      release-created: ${{ steps.release-please.outputs.release-created }}
      version: ${{ steps.release-please.outputs.version }}

  publish:
    name: Publish
    needs: release
    if: ${{ needs.release.outputs.release-created }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Publish extension
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
          VERSION: ${{ needs.release.outputs.version }}
        run: npx vsce publish "$VERSION"
